= Dictionary of Multilingual Terminology in Humanitarian Language Exchange
// EticaAI, Collaborators_of <etica.of.a.ai@gmail.com>; Rocha, Emerson <rocha@ieee.org>
:toc: 1
:toclevels: 5
:sectlinks: 1

TIP: While this documentation is not finalized, please refer to https://hxlstandard.org/ and HXLTM exported formats which do have formalized strict structure (TBX, TMX, XLIFF)

WARNING: This is a *work in progress* documentation about relationship from HXLTM on tabular format equivalent on XML-like (structured formats).
         It's not finalized.


== General idea

[#conceptum-linguam-terminum]
=== Concept, language and term

While HXLTM is an stricter subset of HXL
(which make feasible to import and export to other data formats related to terminology and translation)
it tend to be easier to undestand that the approach by breaking the data in 3 + 1 blocks:

1. **Concept-level**
2. **Language-level**
3. **Term-level**
4. **_Fourth-level_**

For data low level data exchange, _in general_,
the `1. Concept-level`, `2. Language-level` and `3. Term-level` are aligned with
link:++#TBX++[TermBase eXchange (TBX)] and (not always with these terms) link:++#UTX++[Universal Terminology eXchange (UTX)].
General experience with terminology, even as an user of https://iate.europa.eu/fields-explained[Europe IATE],
https://unterm.un.org/[UNTERM] or end user interface with similar propose,
is helpful to undestand how HXLTM use these levels.

The **`4. _Fourth-level_`**
(not used with this nomenclature on other standards) when used on HXLTM documentation means arbitrary data related to the entire dataset _knows_ about itself and does not fit as _Abstract_ of any of the 3 levels (not even the `1. **Concept-level**`).
This can be used, for example, as a base to store **in every data row** title or description of an TBX.
Since this use case is uncommon (relevant only if you are storing several datasets from different sources)
will not the explaned here.

IMPORTANT: If this is your first time doing lexicography work
           (e.g, practical dictionary compiling, like merging work from volunteers)
           It's really important to understand that in the real world,
           natural languages do not have one to one equivalent and most difficulties for translators actually are shitty source terms to translate.
           Such issues are less common in prose (sentences, paragraphs)
           but terms (often one or few words, in special abbreviations) need more context.
           Even paid professional translators are likely to have poor performance compared to volunteer translations if you manage to document better what source material means.
           One reason for this difference is even professional translators will _faithfully translate_ whatever was the source terms,
           even if this means literal translations.

TIP: If you perceive too many literal translations,
     either improve context for each concept,
     or at bare minimum allow one reviewned version of initial text based on feedback of one or more translators.

#TODO: define a suggested language attribute for such reviewed translations (2021-11-29T21:49:00Z)#


////
- On the issue with gender on the Core-Person-Vocabulary
** https://github.com/SEMICeu/Core-Person-Vocabulary/issues/13
////

// TIP: One common symptom of literal translations is lack of context.

// Not only this, but often means target languages have either to create new terms from bad source terms so generic that are unusable for serious work.

////
for example the relationship between linguistic datasets,
information about how it is processed, etc.
// It can also be used to save on HXLTM tabular format what would be on metadata from XML containers with one issue:
// storing such metadata in *every* row is very verbose.

TIP: If you are _only_ a end user,
     you can ignore referentes to the `4. _Fourth-level_`.
     But the idea of _Concrete vs Abstract_ is relevant as it can affect how you label data.
////

[#item-meta]
=== Concrete vs Abstract
The way `1. Concept-level`, `2. Language-level` and `3. Term-level` expressions used on HXLTM also have two options of base hashtag which could be explained as making the data either concrete
(like the main objective intended to be always used)
or abstract (like generic metadata or data, like very new `2. Language-level` /  `3. Term-level` columns, that are not ready yet).

////
Note that most terminology formats are designed to only export final data.
By default HXLTM tools when importing from then the terms will save with HXL hashtags that are "concrete".
////

////
The optimized use case of HXLTM is focused on emergency response **and** multilingual content:
There is special care for languages which could not be worked on places like Europe IATE or other humanitarian online terminology frontend because are not prioritized.
////

////
While most examples of HXLTM made by HXP-CPLP are already publish CSVs, XLSXs and Google Sheets,
the HXLTM tooling can be used to
////
////
This distinction is made both to allow ad-hoc differentiation when parsing HXL directly,
without HXLTM-aware tools,
by simply changing the base tag.

TIP: For example you may be doing a collaborative translation but tools that fetch you data and publish may be marked to not export entire coluns (like new translations) that are marked as abstract.
////

////
NOTE: tools parsing HXLTM tables directly should undestand 

Another reason is to allow 

and also to allow some level of tolerance when validating data:
if a data source needs to be processed both by old and new tools,
this feature can be explored
////

=== HXLTM on tabular container

// Such extra attribute also match the  `1. Concept-level`, `2. Language-level` and `3. Term-level` idea.
The baseline HXL hashtags _(when using Latin script)_ are the following:

1. Concept-level
** `#item+conceptum`
** `#meta+conceptum` (abstract)
2. Language-level
** `#item+linguam+\\__linguam__`
** `#meta+linguam+\\__linguam__` (abstract)
3. Term-level
** `#item+terminum+\\__linguam__`
** `#meta+terminum+\\__linguam__` (abstract)
4. _Fourth-level_
** `#x_meta`

Trivia: Compared to the HXLStandard,
while the HXLTM reference tools will allow mix with other HXL generic tags (for example, `#date`),
the most optimized operations for formats that are not tabular HXLTM will work with only `#item` and `#meta` *and* require an extra base HXL attribute.
Without this extra attribute HXLTM tools will assume you are mixing generic HXL.

=== Use with not typical linguistic content

* https://tools.ietf.org/search/bcp47
** https://en.wikipedia.org/wiki/ISO_15924
** https://en.wikipedia.org/wiki/ISO_639-3

==== One non typical language

In addition to allow mix linguistic content
(for example, extra metadata, codes, etc)
is also possible to reuse HXLTM tools for no linguistic content at all:
you just need _create_ your own private language code.
Since HXLTM operates using BCP47,
the most generic base to use is ISO 15924 `Zyyy`` and ISO 639-3 `zxx``:
`zxx-Zyyy` (or `+i_zxx+is_Zyyy`)

==== Several non typical languages
Both use of BCP47 one or more private tags,
`zxx-Zyyy-x-privatum` (or `+i_zxx+is_Zyyy+ix_privatum`),
or language codes and language scripts,
like `qaa-Zyyy` (or `+i_qaa+is_Zyyy`),
can be used.

==== Text descriptions for non typical languages

When using HXLTM to encode either one non or several typical languages,
for example quick examples of programming hello worlds,
you can writte the human descriptions as definitions of a real natural language.

== HXL base hashtag for HXLTM
When working with HXLTM on a tabular container, it is necessary specify a base HXL hashtag.

=== `+#item+`

Concrete (see <<#item-meta>>) implementation of any the 3 base groups (See <<#conceptum-linguam-terminum>>).

=== `+#meta+`

Abstract (see <<#item-meta>>) implementation of any the 3 base groups (See <<#conceptum-linguam-terminum>>).

=== Other cases

==== Behavior for HXL hashtags not know by HXLTM
* See https://hxlstandard.org/standard/dictionary/[]

Datasets with valid HXL base hashtags
(but not explicitly known as part of HXLTM, like your user-configurable Ontologia)
can be used when creating more generic exporters from tabular formats.

NOTE: Operations related to transpose data (see <<#__linguam__>>),
      which already are very advanced to simplify for the end user,
      did not explicitly have promises that will keep it working.
      If you have generic HXL tags that want to transpose,
      the more reliable way would be attach explicitly to one of the
      <<#conceptum-linguam-terminum>>.

==== Behavior for columns without HXL hashtags (but tabular dataset already is HXLated)
HXLTM tools will not create **new** columns on HXLTM tabular datasets without HXL hashtags.
But it _MAY_ re-export columns without HXL headings when no advanced transposition is done and MAY allow exporters specifying exact column order of original dataset.

Rationale: HXLTM tools, even for datasets with text headings (but not HXL hashtags,
even unknown by HXLTM, but valid in generic HXL),
are unlikely to reliably know what to do.

NOTE: if you are creating an exporter using HXLTM (not an external tool) please consider using some custom base hashtag or new attribute.
      This allows your implementation to be more generic and less likely to break if column order changes.

==== Behavior for tabular dataset without any HXL hashtag (like generic CSV, XLSX, Google Sheets, ...)
Except for tools specialized to import
(for example, `hxltmdexml`)
HXLTM requires already HXLated dataset.
You can use HXLStandard tools to map any container (which is beyond CSV or local files)
to add the tags used by HXLTM.

== HXL attributes for HXLTM

TIP: An HXLTM dataset can contain much more attributes than the ones listed here,
     especially if mixed with general HXL Standard tags.
     One of the main reasons for this documentation is document what exist
     (or is planned to be implemented)
     tools that make advanced conversions using these attributes.
     *You are free to create your own attributes neither documented on HXLTM or HXL Standard*.

// TIP: You are free to create your own attributes and HXL Standard tools are more flexible than HXLTM.

=== `+conceptum`
Definitionem::
HXL attribute for **Concept-level** representation (See <<#conceptum-linguam-terminum>>).

==== `+conceptum+codicem`
Definitionem::
The unique code (on context of current dataset) for the concept.
Usum::
* For columns not containing linguistic data or that need to interoperate with HXL Standard tools,
  use HXL Standard have `+code`.
  ** Example: `#meta+code` (HXL) vs `#item+conceptum+codicem` (HXMTL)

[#linguam__linguam__]
=== `+linguam+\\__linguam__`
Definitionem::
HXL attribute required for **Language-level** representation (See <<#conceptum-linguam-terminum>>).

[#linguam__linguam__definitionem]
==== `+linguam+\\__linguam__+definitionem`

While each language can have several terms, the textual definition should be defined at language level.

NOTE: HXLTM intentionally **NOT** allows set textual definition on Concept-level.

Required additional atttribute: <<#\\__linguam__>>

[#terminum__linguam__]
=== `+terminum+\\__linguam__`
Definitionem::
HXL attribute required for **Term-level** representation (See <<#conceptum-linguam-terminum>>).

Required additional atttribute: <<#\\__linguam__>>

[#__linguam__]
=== `+__linguam__+`
Both user documentation and ontologia file uses `+__linguam__+` to represent an unlimited (but predictable) number of HXL attributes related to express the idea of language (often a language code).

Since HXLTM can work with both with Wide and narrow data
(see https://en.wikipedia.org/wiki/Wide_and_narrow_data[Wikipedia for Wide and narrow data
])
additional differentiation is done with attributes that mention the language explicitly or implicitly.

NOTE: The default format used on most HXLTM documentation is the `+__linguam__+` (explicitum).
      This tend to be easier _(at least for tasks not related to review language codes themselves)_ for end users edit raw data **and** allow HXLTM tools work with memory efficient way:
      not only all languages are know upfront,
      but with only a small number of rows already it is possible to know all information related to a concept and export data immediately, freeing memory.

[#__linguam__explicitum]
==== `+__linguam__+` (explicitum)

#TODO: this is a draft. Needs be documented later#

[#__linguam__implicitum]
==== `+__linguam__+` (implicitum)

There are only two grouped ways to express when the language is not explicitly already present on the HXL hashtags used by HXLTM.
They are not part of HXL Standard 1.1 (but still could be somewhat used when transposing data without HXLTM-aware tools).
The difference betwen the groups is the following: one contains the data about what languages is used by the other.

* <<#ib_h_de_*>>: uses data from
* <<#ib_h_est_*>>: have data of

=== `+ib_*` (BCP47 extension base prefix)
* BCP47 (prefix)
** https://tools.ietf.org/rfc/bcp/bcp47


[#ib_g_*]
==== `+ib_g_*` (BCP 47 informal Extension G - Glottocode prefix)
Definitionem::
* BCP 47 informal Extension G - Glottocode prefix for Glottocode language codes
Referens::
* https://glottolog.org/
* https://hxltm.etica.ai/
Usum::
* Note: this prefix was not formally submitted as IETF RFC.
  Yet is relevant enough to be used beyond private prefix `-x-`

[#ib_h_*]
==== `+ib_h_*` (BCP 47 informal Extension H - HXLTM prefix)
Definitionem::
* BCP 47 informal Extension H - Use on HXLTM (prefix)
Referens::
* https://hxltm.etica.ai/
Usum::
* Note: this prefix was not formally submitted as IETF RFC.
  Yet is relevant enough to be used beyond private prefix `-x-`

// ----
// %%
// Identifier:
// Description:
// Comments:
// Added:
// RFC:
// Authority:
// Contact_Email:
// Mailing_List:
// URL:
// %%
// ----

[#ib_h_de_*]
===== `+ib_h_de_*`
Definitionem::
The language code of this column is stored as the value of an equivalent column with the name <<#ib_h_est_*>>.

[#ib_h_de_linguam]
====== `+ib_h_de_linguam`
Definitionem::
The language code of this column is stored as the value of an equivalent column with the name <<#ib_h_est_linguam>>.

[#ib_h_de_linguam_fontem]
====== `+ib_h_de_linguam_fontem`
Definitionem::
The language code of this column is stored as the value of an equivalent column with the name <<#ib_h_est_linguam_fontem>>.

[#ib_h_de_linguam_objectivum]
====== `+ib_h_de_linguam_objectivum`
Definitionem::
The language code of this column is stored as the value of an equivalent column with the name <<#ib_h_est_linguam_objectivum>>.

[#ib_h_est_*]
===== `+ib_h_est_*`
Definitionem::
The values of each row on this column represent the code referenced on another column with attribute <<#ib_h_de_*>>.

[#ib_h_est_linguam]
====== `+ib_h_est_linguam`
Definitionem::
The values of each row on this column represent the code referenced on another column with attribute <<#ib_h_de_linguam>>.

[#ib_h_est_linguam_fontem]
====== `+ib_h_est_linguam_fontem`
Definitionem::
The values of each row on this column represent the code referenced on another column with attribute <<#ib_h_de_linguam_fontem>>.

[#ib_h_est_linguam_objectivum]
====== `+ib_h_est_linguam_objectivum`
Definitionem::
The values of each row on this column represent the code referenced on another column with attribute <<#ib_h_de_linguam_objectivum>>.

[#ib_t_*]
==== `+ib_t_*` (BCP 47 Extension T - Transformed Content)
Titulum::
* BCP 47 Extension T - Transformed Content
Referens::
* https://datatracker.ietf.org/doc/html/rfc6497


////

////

==== `+ib_u_*` (BCP 47 Extension U)
Titulum::
* Unicode Extensions for BCP 47
Referens::
* https://cldr.unicode.org/index/bcp47-extension
* https://datatracker.ietf.org/doc/html/rfc6067

////

%%
Identifier: u
Description: Unicode Locale
Comments: Subtags for the identification of language and cultural
    variations.  Used to set behavior in locale APIs.  Data is
    located in the "common/bcp47" directory inside the referenced
    URL.  Unicode Technical Standard #35 (LDML) provides additional
    reference material defining the keys and values.
    For more details please see
    <http://cldr.unicode.org/index/bcp47-extension>.
Added: 2010-09-02
RFC: RFC 6067
Authority:     Unicode Consortium
Contact_Email: cldr-contact@unicode.org
Mailing_List:  cldr-users@unicode.org
URL: http://www.unicode.org/Public/cldr/latest/core.zip
%%

////


==== `+ib_x_*` (BCP 47 private extensions)
Titulum::
* BCP47 Private Use Subtags
Referens::
* https://www.rfc-editor.org/rfc/rfc4646#section-2.2.7

NOTE: As per BCP47, each tag must be from 2 to 8 characters long.
      This means that terms like _nomen periculosum_ are shortened to _periculo_.

===== `+ib_x_ambiguum`

Titulum::
* BCP47 Private Use Subtags, HXLTM convention, ambiguum
Definitionem::
* _ambiguous names, nomina ambigua, have been used with more than one meaning_
Referens::
* https://en.wikipedia.org/wiki/Nomen_dubium
* https://en.wiktionary.org/wiki/ambiguus#Latin
Usum::
* Consider using <<#ib_x_periculo>> if the ambigity is not just confuding from nomenclature point of view,
  but potentially harmful on real world usage.

[#ib_x_dubium]
===== `+ib_x_dubium`
Titulum::
* BCP47 Private Use Subtags, HXLTM convention, dubium
Definitionem::
* a _nomen dubium_ (Latin for "doubtful name", plural nomina dubia) is a scientific name that is of unknown or doubtful application.
Referens::
* https://en.wikipedia.org/wiki/Nomen_dubium 
Usum::
* Consider use more specific <<#ib_x_periculo>> or <<#ib_x_ambigua>> when applicable.

[#ib_x_periculo]
===== `+ib_x_periculo`
Titulum::
* BCP47 Private Use Subtags, HXLTM convention, periculo
Definitionem::
* perilous names, nomina periculosa, names that may lead to accidents endangering life or health or with potential serious economic consequences
Referens::
* https://en.wikipedia.org/wiki/Nomen_dubium
* https://en.wiktionary.org/wiki/nomina_periculosa
Usum::
* No specific usage note. Follow the definition and external references.

== Base tags used when HXLTM on XML-like container

NOTE: this section does not include other formalized specifications
      (mostly TBX, but we implicitly apply this too to every imported/exported format).

[source,xml]
----
include::../testum/hxltm-salve-mundi.hxltm.xml[]
----

////
hxltmdexml --agendum-linguam lat-Latn,arb-Arab testum/hxltm-salve-mundi.hxltm.xml > testum/resultatum/hxltm-salve-mundi.tm.hxl.csv

hxltmcli --agendum-linguam eng-Latn@en,por-Latn@pt hxl-non-hxltm-exemplum.hxl.csv

linguacodex --de_codex por-Latn-g-port1283-t-eng --de_bcp47_simplex | jq

hxltmcli de-extraneum/hxltm-multi-linguam-in-columnam-v.csv

////
[source,bash]
----
hxltmdexml --agendum-linguam lat-Latn,arb-Arab testum/hxltm-salve-mundi.hxltm.xml

----

[source,csv]
----
include::../testum/resultatum/hxltm-salve-mundi.tm.hxl.csv[]
----

_TODO: make it work with new format `hxltmcli hxltm-exemplum-glossarium-minimum.tm.hxl.csv --objectivum-TMX`_

////
== Drafts

https://www.tbxinfo.net/summary-of-changes-in-iso-30042/

Concept level

#item+conceptum+codicem


Language level
---------
#item+linguam+i_la+lat+is_Latn

#item+linguam+i_la+lat+is_Latn+dedinitionem

Term level
---------
#item+linguam+i_la+lat+is_Latn+terminum+tem (verboso demais)



#item+terminum+i_la+lat+is_Latn+rem
>>>> a coisa
#item+terminum+i_la+lat+is_Latn+typum
>>>>> term, shortForm, abbr,...


////

////

- https://aclanthology.org/2020.lrec-1.603.pdf
- https://github.com/trimed-dialect/TriMED/tree/master/Modules/TBX_trimed_module
////

== See also

=== HXLStandard
The main inspiration
(and strongly recommended reading for implementers trying to add advanced features)
is the https://hxlstandard.org/[The Humanitarian Exchange Language Standard].

Note that the HXL Standard is more flexible than HXLTM.

Did you know that HXL is public domain? That's fantastic!

[#UTX]
=== Universal Terminology eXchange UTX

- http://www.aamt.info/english/utx/[UTX (Universal Terminology eXchange)]
- http://www.aamt.info/japanese/utx/[用語集形式UTX]

After HXL itself, UTC is one strong inspiration for HXLTM.

Did you know that UTX is public domain? That's fantastic!

[#TBX]
=== TermBase eXchange (TBX) (the creative commons licensed)

* https://www.tbxinfo.net/wp-content/uploads/2016/10/tbx_oscar.pdf
* http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf

_TODO: add more information here_
