# SPDX-License-Identifier: Unlicense OR 0BSD
# .github/workflows/hxltm-computo_testum.yml

# Trivia:
# - "HXLTM", https://hxltm.etica.ai/
# - "computō",https://en.wiktionary.org/wiki/computus#Latin
# - "testum", https://en.wiktionary.org/wiki/testum#Latin
# - "referēns", https://en.wiktionary.org/wiki/referens#Latin

# https://en.wiktionary.org/wiki/computus

name: hxltm-computo_testum

# name: testum

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.7, 3.8, 3.9, 3.10]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions

    - name: Test with tox
      run: tox

      # TODO: remove the continue-on-error
      continue-on-error: true